//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public CustomerDetail()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int customerid { get; set; }
        public string customername { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> pin { get; set; }
        public string telno { get; set; }
        public string mobileno { get; set; }
        public Nullable<System.DateTime> registrationdate { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
