//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaTourProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySubCategory
    {
        public CategorySubCategory()
        {
            this.PackageCompleteDetails = new HashSet<PackageCompleteDetail>();
        }
    
        public int catsubid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string categoryname { get; set; }
        public string categoryimage { get; set; }
        public Nullable<int> subcategoryid { get; set; }
        public string eofflag { get; set; }
    
        public virtual ICollection<PackageCompleteDetail> PackageCompleteDetails { get; set; }
    }
}
