//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaTourProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatePackageDetail
    {
        public DatePackageDetail()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int datepackageid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string reversetripflag { get; set; }
        public Nullable<int> packageid { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual PackageCompleteDetail PackageCompleteDetail { get; set; }
    }
}
