//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaTourProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCompleteDetail
    {
        public PackageCompleteDetail()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.DatePackageDetails = new HashSet<DatePackageDetail>();
            this.Itineraries = new HashSet<Itinerary>();
            this.PriceDetails1 = new HashSet<PriceDetails1>();
        }
    
        public int packageid { get; set; }
        public string tourname { get; set; }
        public string tourimage { get; set; }
        public string description { get; set; }
        public Nullable<int> catsubid { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual CategorySubCategory CategorySubCategory { get; set; }
        public virtual ICollection<DatePackageDetail> DatePackageDetails { get; set; }
        public virtual ICollection<Itinerary> Itineraries { get; set; }
        public virtual ICollection<PriceDetails1> PriceDetails1 { get; set; }
    }
}
